general:
  startup_commands: ["shell-exec yasb"]
  focus_follows_cursor: false
  toggle_workspace_on_refocus: false
  cursor_jump:
    enabled: true
    trigger: "window_focus"
    hide_method: 'cloak'
    show_all_in_taskbar: false
gaps:
  inner_gap: "12px"
  outer_gap:
    top: "12px"
    right: "12px"
    bottom: "12px"
    left: "12px"

window_effects:
  focused_window:
    border:
      enabled: false
      color: "#a6e3a1"
    hide_title_bar:
      enabled: true

  other_windows:
    border:
      enabled: false
      color: "#313244"
    hide_title_bar:
      enabled: true
    transparency:
      enabled: false
      opacity: '96%'
window_behavior:
  initial_state: "tiling"
  state_defaults:
    floating:
      centered: true
      shown_on_top: false
    fullscreen:
      maximized: false
      shown_on_top: false
workspaces:
  - name: "1"
    display_name: "I"
  - name: "2"
    display_name: "II"
  - name: "3"
    display_name: "III"
  - name: "4"
    display_name: "IV"
  - name: "5"
    display_name: "V"
  - name: "6"
    display_name: "VI"
  - name: "7"
    display_name: "VII"
  - name: "8"
    display_name: "VIII"
  - name: "9"
    display_name: "IX"
window_rules:
  - commands: ['ignore']
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: 'zebar' }

      # Ignore PowerToys Command Palette
      - window_title: { equals: 'Command Palette' }
        window_class: { equals: 'WinUIDesktopWin32WindowClass' }

      # Ignore Keyviz
      - window_process: { equals: 'Keyviz.exe' }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }

      # Ignore rules for various 3rd-party apps.
  - commands: ["set-floating"]
    match:
      - window_process: { equals: 'Photoshop' }
        window_class: { not_regex: 'Photoshop' }

      # Ignore child windows from Adobe Illustrator
      - window_process: { equals: 'Illustrator' }
        window_class: { not_regex: 'Illustrator' }

      # Ignore child windows from Adobe After Effects
      - window_process: { equals: 'AfterFX' }
        window_class: { not_regex: 'AfterFX' }

      # Ignore child windows from Adobe Premiere Pro
      - window_process: { equals: 'Adobe Premiere Pro' }
        window_class: { not_regex: 'Premiere Pro' }

      - window_process: { equals: 'PowerToys' }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: 'PowerToys' }
        window_title: { regex: '.*? - Peek' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper' }
      - window_process: { equals: 'EXCEL' }
        window_class: { not_regex: 'XLMAIN' }
      - window_process: { equals: 'WINWORD' }
        window_class: { not_regex: 'OpusApp' }
      - window_process: { equals: 'POWERPNT' }
        window_class: { not_regex: 'PPTFrameClass' }
      - window_process: { equals: 'PowerToys' }
    
binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: "resize"
    keybindings:
      - commands: ["resize --width -2%"]
        bindings: ["h", "left"]
      - commands: ["resize --width +2%"]
        bindings: ["l", "right"]
      - commands: ["resize --height +2%"]
        bindings: ["k", "up"]
      - commands: ["resize --height -2%"]
        bindings: ["j", "down"]
      - commands: ["wm-disable-binding-mode --name resize"]
        # Press enter/escape to return to default keybindings.

        bindings: ["escape", "enter"]

  - name: "wm-redraw"
    keybindings:
      - commands: ["wm-redraw"]
        bindings: ["alt+shift+y"]

  - name: "pause"
    # When enabled, all keybindings are disabled except for alt+shift+p which

    # returns to default keybindings.
keybindings:
  # Shift focus in a given direction.
  - commands: ['focus --direction left']
    bindings: ['alt+h', 'alt+left']
  - commands: ['focus --direction right']
    bindings: ['alt+l', 'alt+right']
  - commands: ['focus --direction up']
    bindings: ['alt+k', 'alt+up']
  - commands: ['focus --direction down']
    bindings: ['alt+j', 'alt+down']

  # Move focused window in a given direction.
  - commands: ['move --direction left']
    bindings: ['alt+shift+left']
  - commands: ['move --direction right']
    bindings: ['alt+shift+right']
  - commands: ['move --direction up']
    bindings: ['alt+shift+up']
  - commands: ['move --direction down']
    bindings: ['alt+shift+down']

  # Resize focused window by a percentage or pixel amount.
  - commands: ['resize --width -1%']
    bindings: ['alt+.']
  - commands: ['resize --width +1%']
    bindings: ['alt+,']
  - commands: ['resize --height +1%']
    bindings: ['alt+;']
  - commands: ['resize --height -1%']
    bindings: ['alt+l']

  - commands: ['resize --width -20%']
    bindings: ['alt+shift+.']
  - commands: ['resize --width +20%']
    bindings: ['alt+shift+,']
  - commands: ['resize --height +20%']
    bindings: ['alt+shift+;']
  - commands: ['resize --height -20%']
    bindings: ['alt+shift+l']

  # As an alternative to the resize keybindings above, resize mode enables
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  # the name 'resize'.
  #- commands: ['wm-enable-binding-mode --name resize']
  #  bindings: [' ']

  # Disables window management and all other keybindings until alt+shift+p
  # is pressed again.
  #- commands: ['wm-toggle-pause']
  #  bindings: ['alt+shift+p']

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ['toggle-tiling-direction']
    bindings: ['alt+v']

  - commands: ['toggle-tiling']
    bindings: ['alt+shift+q']

  # Change focus from tiling windows -> floating -> fullscreen.
  - commands: ['wm-cycle-focus']
    bindings: ['alt+b']

  # Change the focused window to be floating.
  - commands: ['toggle-floating --centered']
    bindings: ['alt+shift+a']

  # Change the focused window to be fullscreen.
  - commands: ['toggle-fullscreen']
    bindings: ['alt+shift+s']

  # Minimize focused window.
  - commands: ['toggle-minimized']
    bindings: ['alt+w']

  # Close focused window.
  - commands: ['close']
    bindings: ['alt+q']

  # Kill GlazeWM process safely.
  #- commands: ['wm-exit']
  #  bindings: ['alt+shift+e']

  # Re-evaluate configuration file.
  - commands: ['wm-reload-config']
    bindings: ['alt+shift+]']

  # Redraw all windows.
  - commands: ['wm-redraw']
    bindings: ['alt+shift+w']

  # Launch CMD terminal. Alternatively, use `shell-exec wt` or
  # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start Windows
  # Terminal and Git Bash respectively.
  - commands: ['shell-exec msedge']
    bindings: ['alt+shift+r']
  - commands: ['shell-exec wt']
    bindings: ['alt+shift+e']

  # Focus the next/previous active workspace defined in `workspaces` config.
  - commands: ['focus --next-active-workspace']
    bindings: ['alt+s']
  - commands: ['focus --prev-active-workspace']
    bindings: ['alt+a']

  # Focus the workspace that last had focus.
  #- commands: ['focus --recent-workspace']
  #  bindings: ['alt+d']

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ['focus --workspace 1']
    bindings: ['alt+1']
  - commands: ['focus --workspace 2']
    bindings: ['alt+2']
  - commands: ['focus --workspace 3']
    bindings: ['alt+3']
  - commands: ['focus --workspace 4']
    bindings: ['alt+4']
  - commands: ['focus --workspace 5']
    bindings: ['alt+5']
  - commands: ['focus --workspace 6']
    bindings: ['alt+6']
  - commands: ['focus --workspace 7']
    bindings: ['alt+7']
  - commands: ['focus --workspace 8']
    bindings: ['alt+8']
  - commands: ['focus --workspace 9']
    bindings: ['alt+9']

  # Move the focused window's parent workspace to a monitor in a given
  # direction.
  - commands: ['move-workspace --direction left']
    bindings: ['alt+shift+p']
  - commands: ['move-workspace --direction right']
    bindings: ['alt+shift+f']
  - commands: ['move-workspace --direction up']
    bindings: ['alt+shift+d']
  - commands: ['move-workspace --direction down']
    bindings: ['alt+shift+o']

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ['move --workspace 1', 'focus --workspace 1']
    bindings: ['alt+shift+1']
  - commands: ['move --workspace 2', 'focus --workspace 2']
    bindings: ['alt+shift+2']
  - commands: ['move --workspace 3', 'focus --workspace 3']
    bindings: ['alt+shift+3']
  - commands: ['move --workspace 4', 'focus --workspace 4']
    bindings: ['alt+shift+4']
  - commands: ['move --workspace 5', 'focus --workspace 5']
    bindings: ['alt+shift+5']
  - commands: ['move --workspace 6', 'focus --workspace 6']
    bindings: ['alt+shift+6']
  - commands: ['move --workspace 7', 'focus --workspace 7']
    bindings: ['alt+shift+7']
  - commands: ['move --workspace 8', 'focus --workspace 8']
    bindings: ['alt+shift+8']
  - commands: ['move --workspace 9', 'focus --workspace 9']
    bindings: ['alt+shift+9']