watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ['*'] 
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: true
      round_corners: false
      border_color: None
    animation:
      enabled: False
      duration: 0
    window_flags:
      always_on_top: false
      windows_app_bar: true
      hide_on_fullscreen: true
    dimensions:
      width: "100%"
      height: 38
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left:
        [
          "glazewm_workspaces",
          "active_window",
          "language",
          "gpu",
        ]
      center:
        [
          "clock",
        ]
      right:
        [
          "media",
          "volume",
          "memory",
          "battery",
          "notifications",
          "wifi",
          "power_menu"
        ]
widgets:
  gpu:
    type: "yasb.gpu.GpuWidget"
    options:
      label: "  G: {info[temp]}°C  |"
      label_alt: "  G: {info[temp]}°C | {info[mem_used]} / {info[mem_total]}  |"
      update_interval: 2000
      gpu_thresholds:
        low: 25
        medium: 50
        high: 90
      histogram_icons:
        - "\u2581" # 0%
        - "\u2581" # 10%
        - "\u2582" # 20%
        - "\u2583" # 30%
        - "\u2584" # 40%
        - "\u2585" # 50%
        - "\u2586" # 60%
        - "\u2587" # 70%
        - "\u2588" # 80%+
      histogram_num_columns: 8
      callbacks:
        on_left: "toggle_label"
  language:
    type: "yasb.language.LanguageWidget"
    options:
      label: "|  {lang[country_code]}  |"
      label_alt: "{lang[full_name]}"
      update_interval: 1
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      language_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
        offset_top: 0
        offset_left: 0
        show_layout_icon: true
        layout_icon: "\uf11c"
      label_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "Offline!"
      hide_empty_workspaces: true
      hide_if_offline: false
      container_padding: 
        top: 0
        left: 8
        bottom: 0
        right: 8
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "|  !!"
      label_alt: "|  NOTIF: {count}"
      hide_empty: false
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "toggle_label"
        on_middle: "toggle_label"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 13
      gradient: 1
      reverse: 0
      sensitivity: 100
      foreground: "#91cc86"
      gradient_color_1: '#91cc86'
      gradient_color_2: '#91cc86'
      gradient_color_3: '#91cc86'
      bars_number: 8
      bar_spacing: 2
      bar_width: 4
      sleep_timer: 0
      framerate: 144
      hide_empty: true
      container_padding:
        top: 2
        left: 11
        bottom: 1
        right: 0
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "|<span>B: {percent}%</span>"
      label_alt: "|<span>{icon}</span> {percent}%"
      charging_options:
        icon_format: "{charging_icon}"
      status_icons:
        icon_charging: "AC"
        icon_critical: "CRITICAL"
        icon_low: "LOW"
        icon_medium: "MED"
        icon_high: "\udb80\udc80"
        icon_full: "\udb80\udc79"
      status_thresholds:
        critical: 10
        low: 30
        medium: 75
        high: 85
        full: 100
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "|<span>M: {virtual_mem_used}</span>"
      label_alt: "|  \uefc5 {virtual_mem_used}/{virtual_mem_total}"
      update_interval: 5000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 0
  media:
      type: "yasb.media.MediaWidget"
      options:
        label: "{title}"
        label_alt: "ARTIST: {artist}"
        max_field_size:
          label: 20
          label_alt: 20
        show_thumbnail: false
        controls_only: false
        controls_left: true
        hide_empty: true
        thumbnail_alpha: 250
        thumbnail_padding: 8
        thumbnail_corner_radius: 0
        callbacks:
          on_left: "toggle_media_menu"
          on_middle: "toggle_play_pause"
          on_right: "toggle_label"
        icons:
          prev_track: ""
          next_track: ""
          play: ""
          pause: ""
        media_menu:
          blur: true
          round_corners: false
          round_corners_type: "normal"
          border_color: "system"
          alignment: "right"
          direction: "down"
          offset_top: 8
          offset_left: -2
          thumbnail_corner_radius: 2
          thumbnail_size: 75
          max_title_size: 21
          max_artist_size: 28
          show_source: false
        media_menu_icons:
          play: "\uf04b"
          pause: "\uf04c"
          prev_track: "\uf04a"
          next_track: "\uf04e"
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "|  {win[title]}"
      label_alt: "|  {win[class_name]}"
      label_no_window: "|  Windows Desktop"
      label_icon: false
      label_icon_size: 14
      max_length: 30
      max_length_ellipsis: "..."
      monitor_exclusive: true
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      tooltip: false
      label: "|<span>V: {level}</span>"
      label_alt: "|  {icon}"
      volume_icons:
        - "MUTE"  # Icon for muted
        - "\uf026"  # Icon for 0-10% volume
        - "\uf027"  # Icon for 11-30% volume
        - "\uf027"  # Icon for 31-60% volume
        - "\uf028"  # Icon for 61-100% volume
      audio_menu:
        blur: true
        round_corners: false
        round_corners_type: 'normal'
        border_color: 'System'
        alignment: 'right'
        direction: 'down'
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "toggle_mute"
        on_middle: "toggle_label"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%d %B  |  %I:%M %p}"
      label_alt: "{%A  |  %d %B %Y  |  %I:%M:%S %p}"
      timezones: []
      calendar:
        blur: true
        show_holidays: true
        direction: down
        alignment: "center"
        holiday_color: "#a1e19c"
  power_menu:
      type: "yasb.power_menu.PowerMenuWidget"
      options:
        label: "|  <span>X</span>"
        uptime: false
        blur: false
        blur_background: false
        animation_duration: 0 # Milisecond 
        button_row: 5 # Number of buttons in row, min 1 max 5
        buttons:
          shutdown: ["","PWR OFF"]
          signout: ["","SIGN OUT"]
          restart: ["","RESTART"]
          hibernate: ["","HIBERNATE"]
          cancel: ["","BACK"]
  wifi:
      type: "yasb.wifi.WifiWidget"
      options:
        label: "|<span>{wifi_icon}</span>"
        label_alt: "|<span>{wifi_icon}</span> {wifi_name}"
        update_interval: 5000
        ethernet_icon: "|  WIRED"
        ethernet_label_alt: "{ip_addr}"
        wifi_icons: [
          "W: 10%",  # Icon for 0% strength
          "W: 25%",  # Icon for 1-24% strength
          "W: 50%",  # Icon for 25-49% strength
          "W: 75%",  # Icon for 50-74% strength
          "W: 100%"   # Icon for 75-100% strength
        ]
        animation:
          enabled: true
          duration: 100
          type: "fadeInOut"
        callbacks:
          on_left: "exec explorer ms-availablenetworks:"
          on_right: "do_nothing"
          on_middle: "toggle_label"